// Supported ISO 4217 currencies matching server/src/utils/currencies.js
export const CURRENCIES = [
  { code: "INR", symbol: "₹", decimals: 2, label: "INR (₹) - Indian Rupee" },
  { code: "USD", symbol: "$", decimals: 2, label: "USD ($) - US Dollar" },
  { code: "EUR", symbol: "€", decimals: 2, label: "EUR (€) - Euro" },
  { code: "GBP", symbol: "£", decimals: 2, label: "GBP (£) - British Pound" },
  { code: "AED", symbol: "د.إ", decimals: 2, label: "AED (د.إ) - UAE Dirham" },
  { code: "AUD", symbol: "A$", decimals: 2, label: "AUD (A$) - Australian Dollar" },
  { code: "CAD", symbol: "C$", decimals: 2, label: "CAD (C$) - Canadian Dollar" },
  { code: "SGD", symbol: "S$", decimals: 2, label: "SGD (S$) - Singapore Dollar" },
  { code: "JPY", symbol: "¥", decimals: 0, label: "JPY (¥) - Japanese Yen" },
  { code: "CNY", symbol: "¥", decimals: 2, label: "CNY (¥) - Chinese Yuan" },
  { code: "CHF", symbol: "CHF", decimals: 2, label: "CHF - Swiss Franc" },
  { code: "NZD", symbol: "NZ$", decimals: 2, label: "NZD (NZ$) - New Zealand Dollar" },
  { code: "ZAR", symbol: "R", decimals: 2, label: "ZAR (R) - South African Rand" },
  { code: "HKD", symbol: "HK$", decimals: 2, label: "HKD (HK$) - Hong Kong Dollar" },
  { code: "SAR", symbol: "﷼", decimals: 2, label: "SAR (﷼) - Saudi Riyal" },
  { code: "QAR", symbol: "﷼", decimals: 2, label: "QAR (﷼) - Qatari Riyal" },
  { code: "KWD", symbol: "د.ك", decimals: 3, label: "KWD (د.ك) - Kuwaiti Dinar" },
  { code: "BHD", symbol: ".د.ب", decimals: 3, label: "BHD (.د.ب) - Bahraini Dinar" },
  { code: "OMR", symbol: "﷼", decimals: 3, label: "OMR (﷼) - Omani Rial" },
  { code: "MYR", symbol: "RM", decimals: 2, label: "MYR (RM) - Malaysian Ringgit" },
  { code: "THB", symbol: "฿", decimals: 2, label: "THB (฿) - Thai Baht" },
  { code: "IDR", symbol: "Rp", decimals: 2, label: "IDR (Rp) - Indonesian Rupiah" },
  { code: "PHP", symbol: "₱", decimals: 2, label: "PHP (₱) - Philippine Peso" },
  { code: "VND", symbol: "₫", decimals: 0, label: "VND (₫) - Vietnamese Dong" },
  { code: "BDT", symbol: "৳", decimals: 2, label: "BDT (৳) - Bangladeshi Taka" },
  { code: "PKR", symbol: "₨", decimals: 2, label: "PKR (₨) - Pakistani Rupee" },
  { code: "LKR", symbol: "₨", decimals: 2, label: "LKR (₨) - Sri Lankan Rupee" },
  { code: "NPR", symbol: "₨", decimals: 2, label: "NPR (₨) - Nepalese Rupee" },
  { code: "SEK", symbol: "kr", decimals: 2, label: "SEK (kr) - Swedish Krona" },
  { code: "NOK", symbol: "kr", decimals: 2, label: "NOK (kr) - Norwegian Krone" },
  { code: "DKK", symbol: "kr", decimals: 2, label: "DKK (kr) - Danish Krone" },
  { code: "PLN", symbol: "zł", decimals: 2, label: "PLN (zł) - Polish Zloty" },
  { code: "BRL", symbol: "R$", decimals: 2, label: "BRL (R$) - Brazilian Real" },
  { code: "MXN", symbol: "$", decimals: 2, label: "MXN ($) - Mexican Peso" },
  { code: "KES", symbol: "KSh", decimals: 2, label: "KES (KSh) - Kenyan Shilling" },
  { code: "NGN", symbol: "₦", decimals: 2, label: "NGN (₦) - Nigerian Naira" },
  { code: "EGP", symbol: "£", decimals: 2, label: "EGP (£) - Egyptian Pound" },
];

export const CURRENCY_MAP = new Map(CURRENCIES.map((c) => [c.code, c]));

